import { NextRequest, NextResponse } from "next/server";

export const runtime = 'edge';

// Vercel 免费版，Edge 函数有严格的执行时间限制，我们设置一个短一点的超时
const FETCH_TIMEOUT = 8000; // 8 秒

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const source = searchParams.get("source");

  if (!source) {
    return new NextResponse("没有提供 source 参数", { status: 400 });
  }

  const sources = source.split("\n").map(s => s.trim()).filter(s => s.length > 0 && s.startsWith('http'));

  if (sources.length === 0) {
    return new NextResponse("提供的链接格式不正确或为空", { status: 400 });
  }

  let combinedContent = `
# Profile generated by EZI SUB
# Timestamp: ${new Date().toISOString()}
`;

  const fetchWithTimeout = (url: string, timeout: number) => {
    return new Promise<Response>((resolve, reject) => {
      const controller = new AbortController();
      const { signal } = controller;
      
      const timeoutId = setTimeout(() => {
        controller.abort();
        reject(new Error(`请求超时: ${url}`));
      }, timeout);

      fetch(url, { 
        headers: { "User-Agent": "ClashConverter" },
        signal,
        // Vercel 缓存策略
        next: { revalidate: 60 } // 缓存60秒
      })
      .then(response => {
        clearTimeout(timeoutId);
        resolve(response);
      })
      .catch(error => {
        clearTimeout(timeoutId);
        reject(error);
      });
    });
  };

  const results = await Promise.allSettled(
    sources.map(s => fetchWithTimeout(s, FETCH_TIMEOUT))
  );

  let successCount = 0;
  for (const result of results) {
    if (result.status === 'fulfilled' && result.value.ok) {
      const text = await result.value.text();
      combinedContent += `\n${text}\n`;
      successCount++;
    } else {
      // 即使某个链接失败，也只是在日志中记录，不影响其他链接
      console.error("抓取失败:", result.status === 'rejected' ? result.reason : result.value.status);
    }
  }
  
  if (successCount === 0) {
    return new NextResponse(`所有订阅链接都抓取失败，请检查链接是否有效或网络是否超时。\n${results.map(r => r.status === 'rejected' ? r.reason.message : '').join('\n')}`, { status: 502 });
  }

  const headers = new Headers({
    "Content-Type": "text/plain;charset=utf-8",
    "Content-Disposition": `attachment; filename="ezi_sub_${new Date().getTime()}.txt"`,
  });

  return new NextResponse(combinedContent, { headers });
}
